# Generated by Django 3.1.4 on 2020-12-19 07:40

import autoslug.fields
from django.db import migrations, models
import truyenhayho.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=250, null=True, populate_from='name', slugify=truyenhayho.models.unicode_slugify, unique=True)),
                ('url', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'story_stories',
            },
        ),
    ]
