# Generated by Django 3.1.4 on 2020-12-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truyenhayho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
