# Generated by Django 3.1.4 on 2020-12-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truyenhayho', '0002_story_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='latest_chapter_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='latest_chapter_url',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
