# Generated by Django 3.1.4 on 2020-12-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truyenhayho', '0003_auto_20201223_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='latest_chapter_name',
            new_name='latest_chap',
        ),
        migrations.RemoveField(
            model_name='story',
            name='latest_chapter_url',
        ),
    ]
