# Generated by Django 3.1.4 on 2020-12-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truyenhayho', '0005_auto_20201224_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
