# Generated by Django 3.1.4 on 2020-12-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truyenhayho', '0006_novel_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='updated',
            new_name='chapter_updated',
        ),
        migrations.RenameField(
            model_name='novel',
            old_name='latest_chap',
            new_name='latest_chapter',
        ),
        migrations.AlterField(
            model_name='novel',
            name='authors',
            field=models.ManyToManyField(blank=True, db_table='novel_novel_authors_rel', to='truyenhayho.Author'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='genres',
            field=models.ManyToManyField(blank=True, db_table='novel_novel_genres_rel', to='truyenhayho.Genre'),
        ),
    ]
