# Generated by Django 3.1.4 on 2020-12-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truyenhayho', '0007_auto_20201224_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='thumbnail_image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
