# Generated by Django 3.1.4 on 2020-12-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truyenhayho', '0008_novel_thumbnail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='latest_chapter',
        ),
        migrations.AddField(
            model_name='novelchapter',
            name='content_updated',
            field=models.BooleanField(default=False),
        ),
    ]
