# Generated by Django 3.1.4 on 2020-12-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truyenhayho', '0010_auto_20201225_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelchapter',
            name='content',
            field=models.BinaryField(),
        ),
    ]
