# Generated by Django 3.1.4 on 2020-12-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truyenhayho', '0011_auto_20201225_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novelchapter',
            old_name='content',
            new_name='binary_content',
        ),
    ]
