# Generated by Django 3.1.4 on 2020-12-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truyenhayho', '0012_auto_20201225_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelchapter',
            name='binary_content',
            field=models.TextField(),
        ),
    ]
