# Generated by Django 3.1.4 on 2020-12-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truyenhayho', '0014_auto_20201225_1205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='novelchapter',
            unique_together={('slug', 'novel'), ('name', 'novel')},
        ),
    ]
