# Generated by Django 3.1.6 on 2021-02-23 21:47

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django_cms.models
import django_cms.utils.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDNServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('server_id', models.CharField(blank=True, max_length=250, null=True)),
                ('endpoint', models.CharField(max_length=250)),
                ('friendly_url', models.CharField(default='https://f000.backblazeb2.com/file/nettruyen/', max_length=250)),
                ('friendly_alias_url', models.CharField(default='https://cdn.nettruyen.vn/file/nettruyen/', max_length=250)),
                ('s3_url', models.CharField(blank=True, max_length=250, null=True)),
                ('last_run', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('running', 'RUNNING'), ('stopped', 'STOPPED')], default='stopped', max_length=10)),
            ],
            options={
                'db_table': 'cdn_server',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='copyright', max_length=30, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cms_footer',
            },
        ),
        migrations.CreateModel(
            name='HtmlPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=250, populate_from='name', slugify=django_cms.models.unicode_slugify, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, default='novel', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_pages',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(blank=True, default='hashtag', max_length=30)),
                ('class_name', models.CharField(blank=True, max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cms_link',
            },
        ),
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_file', models.CharField(choices=[('index', 'Index - Homepage'), ('novel', 'Novel (Comic) Infomation'), ('chapter', 'Chapter'), ('novel_all', 'Novel (Comic) view all'), ('user', 'User'), ('base_footer', 'Base footer'), ('base_navbar', 'Base navbar'), ('base_top_menu', 'Base top menu'), ('base_other_html', 'Base other html')], max_length=250, unique=True)),
                ('params', models.JSONField(blank=True, default=django_cms.models.json_template_default, null=True)),
            ],
            options={
                'db_table': 'cms_template_manager',
                'ordering': ['page_file'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.SmallIntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('extra_class', models.CharField(blank=True, max_length=50, null=True)),
                ('require_logged', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cms_menus',
                'ordering': ['type', 'priority'],
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='InludeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=50, validators=[django_cms.utils.helpers.code_validate])),
                ('include_file', models.CharField(choices=[('chapter_content', 'Chapter content'), ('chapter_list', 'Chapter list'), ('link', 'Links'), ('novel_info', 'Novel (Comic) detail'), ('novel_list', 'Novel (Comic) list - grid'), ('novel_genres', 'Novel (Comic) genres'), ('breadcrumb', 'Breadcrumb'), ('base_footer_info', 'Base footer info'), ('base_top_menu', 'Base top menu'), ('base_navbar_menu', 'Base navbar menu'), ('base_auth_modal', 'Base auth modal'), ('user_profile', 'User profile'), ('comment', 'Comment')], max_length=250)),
                ('params', models.JSONField(blank=True, default=django_cms.models.json_template_default, null=True)),
                ('class_name', models.CharField(max_length=250)),
                ('full_width', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_cms.pagetemplate')),
            ],
            options={
                'db_table': 'cms_template_include',
                'ordering': ['template', 'priority'],
                'unique_together': {('template', 'code')},
            },
        ),
    ]
