# Generated by Django 3.1.6 on 2021-02-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdnserver',
            name='referer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
