# Generated by Django 3.1.6 on 2021-03-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cms', '0003_auto_20210226_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlpage',
            name='type',
            field=models.CharField(blank=True, choices=[('text/plain', 'text/plain'), ('html', 'HTML')], default='html', max_length=30),
        ),
    ]
