# Generated by Django 3.1.5 on 2021-01-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20210113_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
