# Generated by Django 3.1.7 on 2021-03-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cms', '0005_auto_20210311_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='inludetemplate',
            name='full_width',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inludetemplate',
            name='class_name',
            field=models.CharField(default=False, max_length=250),
            preserve_default=False,
        ),
    ]
