# Generated by Django 3.1.7 on 2021-03-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cms', '0006_auto_20210312_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inludetemplate',
            name='class_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
