# Generated by Django 3.1.5 on 2021-01-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_templatemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemanager',
            name='include_file',
            field=models.CharField(choices=[], default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templatemanager',
            name='page_name',
            field=models.CharField(choices=[('chapter.html', 'chapter.html'), ('novel_all.html', 'novel_all.html'), ('novel.html', 'novel.html'), ('index.html', 'index.html')], max_length=250),
        ),
    ]
