# Generated by Django 3.1.5 on 2021-01-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20210116_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemanager',
            name='page_name',
            field=models.CharField(choices=[('chapter.html', 'chapter.html'), ('googlea67d1ab3ec6abe35.html', 'googlea67d1ab3ec6abe35.html'), ('index.html', 'index.html'), ('novel.html', 'novel.html'), ('novel_all.html', 'novel_all.html')], max_length=250),
        ),
    ]
