# Generated by Django 3.1.7 on 2021-06-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_cms', '0009_auto_20210519_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inludetemplate',
            options={'ordering': ['template', 'priority'], 'verbose_name': 'Template widget'},
        ),
        migrations.AlterModelOptions(
            name='pagetemplate',
            options={'ordering': ['page_file'], 'verbose_name': 'Template place'},
        ),
    ]
