# Generated by Django 3.1.5 on 2021-01-18 02:35

import crawl_service.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20210117_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatemanager',
            name='include_file',
        ),
        migrations.RemoveField(
            model_name='templatemanager',
            name='page_name',
        ),
        migrations.AddField(
            model_name='templatemanager',
            name='includes_default',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatemanager',
            name='page_file',
            field=models.CharField(choices=[('index', 'index'), ('chapter', 'chapter'), ('novel', 'novel'), ('novel_all', 'novel_all'), ('footer', 'footer'), ('navbar', 'navbar')], default='', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InludeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, validators=[crawl_service.models.code_validate])),
                ('include_file', models.CharField(choices=[('chapter_content', 'chapter_content'), ('chapter_list', 'chapter_list'), ('link', 'link'), ('novel_info', 'novel_info'), ('novel_list', 'novel_list'), ('breadcrumb', 'breadcrumb')], max_length=250)),
                ('params', models.TextField()),
                ('class_name', models.CharField(max_length=250)),
                ('full_width', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.templatemanager')),
            ],
            options={
                'db_table': 'cms_template_include',
                'unique_together': {('template', 'code')},
            },
        ),
    ]
