# Generated by Django 3.1.5 on 2021-01-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_htmlpage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.SmallIntegerField(default=0)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cms_menus',
            },
        ),
        migrations.AlterField(
            model_name='inludetemplate',
            name='include_file',
            field=models.CharField(choices=[('chapter_content', 'chapter_content'), ('chapter_list', 'chapter_list'), ('link', 'link'), ('novel_info', 'novel_info'), ('novel_list', 'novel_list'), ('novel_genres', 'novel_cat'), ('breadcrumb', 'breadcrumb'), ('footer_info', 'footer_info')], max_length=250),
        ),
    ]
