# Generated by Django 3.1.5 on 2021-02-02 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20210130_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplateManager',
            new_name='PageTemplate',
        ),
    ]
