# Generated by Django 3.1.6 on 2021-02-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20210202_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerinfo',
            name='copyright',
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='type',
            field=models.CharField(blank=True, default='copyright', max_length=30, unique=True),
        ),
    ]
