# Generated by Django 3.1.6 on 2021-02-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20210218_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='required_logged',
            field=models.BooleanField(default=False),
        ),
    ]
