# Generated by Django 3.1.6 on 2021-02-19 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_menu_required_logged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='required_logged',
            new_name='require_logged',
        ),
    ]
