# Generated by Django 3.1.6 on 2021-02-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_auto_20210221_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['type', 'priority']},
        ),
    ]
