# Generated by Django 3.1.5 on 2021-01-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_footerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cms_hashtag',
            },
        ),
    ]
