# Generated by Django 3.1.5 on 2021-01-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20210113_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(blank=True, default='hashtag', max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cms_link',
            },
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
    ]
