# Generated by Django 3.1.5 on 2021-01-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20210113_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[], max_length=250)),
            ],
            options={
                'db_table': 'cms_template_manager',
            },
        ),
    ]
