# Generated by Django 3.1.5 on 2021-01-16 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20210116_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(choices=[('chapter_list.html', 'chapter_list.html'), ('footer.html', 'footer.html'), ('novel_info.html', 'novel_info.html'), ('__breadcrumb.html', '__breadcrumb.html'), ('chapter_content.html', 'chapter_content.html'), ('novel_list.html', 'novel_list.html'), ('link.html', 'link.html'), ('__pagination.html', '__pagination.html'), ('__navbar.html', '__navbar.html')], max_length=250)),
            ],
            options={
                'db_table': 'cms_template_1',
            },
        ),
        migrations.RemoveField(
            model_name='templatemanager',
            name='properties',
        ),
        migrations.CreateModel(
            name='Template2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(max_length=250)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.template1')),
            ],
            options={
                'db_table': 'cms_template_2',
            },
        ),
        migrations.AddField(
            model_name='template1',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.templatemanager'),
        ),
    ]
