# Generated by Django 3.1.5 on 2021-01-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20210118_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='inludetemplate',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inludetemplate',
            name='include_file',
            field=models.CharField(choices=[('chapter_content', 'chapter_content'), ('chapter_list', 'chapter_list'), ('link', 'link'), ('novel_info', 'novel_info'), ('novel_list', 'novel_list'), ('breadcrumb', 'breadcrumb'), ('footer_info', 'footer_info')], max_length=250),
        ),
    ]
