# Generated by Django 3.1.5 on 2021-01-17 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20210116_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='InludeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.TextField()),
                ('cols', models.IntegerField(default=12)),
            ],
            options={
                'db_table': 'cms_template_include',
            },
        ),
        migrations.RemoveField(
            model_name='template2',
            name='template',
        ),
        migrations.RemoveField(
            model_name='templatemanager',
            name='include_file',
        ),
        migrations.DeleteModel(
            name='Template1',
        ),
        migrations.DeleteModel(
            name='Template2',
        ),
        migrations.AddField(
            model_name='inludetemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.templatemanager'),
        ),
    ]
