# Generated by Django 3.1.5 on 2021-01-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20210117_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatemanager',
            old_name='page_name',
            new_name='page_file',
        ),
        migrations.AddField(
            model_name='inludetemplate',
            name='include_file',
            field=models.CharField(choices=[('chapter_list.html', 'chapter_list.html'), ('footer.html', 'footer.html'), ('novel_info.html', 'novel_info.html'), ('chapter_content.html', 'chapter_content.html'), ('novel_list.html', 'novel_list.html'), ('link.html', 'link.html')], default='', max_length=250),
            preserve_default=False,
        ),
    ]
