# Generated by Django 3.1.5 on 2021-01-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20210118_0336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inludetemplate',
            options={'ordering': ['template', 'priority']},
        ),
        migrations.AlterModelOptions(
            name='templatemanager',
            options={'ordering': ['page_file']},
        ),
        migrations.AlterField(
            model_name='inludetemplate',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templatemanager',
            name='includes_default',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
