# Generated by Django 3.1.5 on 2021-01-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20210118_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlpage',
            name='type',
            field=models.CharField(blank=True, default='novel', max_length=30),
        ),
    ]
