# Generated by Django 3.1.5 on 2021-01-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_htmlpage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inludetemplate',
            name='include_file',
            field=models.CharField(choices=[('chapter_content', 'chapter_content'), ('chapter_list', 'chapter_list'), ('link', 'link'), ('novel_info', 'novel_info'), ('novel_list', 'novel_list'), ('novel_genres', 'novel_cat'), ('breadcrumb', 'breadcrumb'), ('footer_info', 'footer_info')], max_length=250),
        ),
    ]
