# Generated by Django 3.1.5 on 2021-01-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20210117_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inludetemplate',
            name='include_file',
            field=models.CharField(choices=[('chapter_content', 'chapter_content'), ('chapter_list', 'chapter_list'), ('link', 'link'), ('novel_info', 'novel_info'), ('novel_list', 'novel_list')], max_length=250),
        ),
    ]
