# Generated by Django 3.1.5 on 2021-01-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20210124_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='class_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
