# Generated by Django 3.1.5 on 2021-01-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20210117_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemanager',
            name='page_file',
            field=models.CharField(choices=[('index', 'index'), ('chapter', 'chapter'), ('novel', 'novel'), ('novel_all', 'novel_all'), ('footer', 'footer'), ('navbar', 'navbar')], max_length=250),
        ),
    ]
