# Generated by Django 3.1.5 on 2021-01-30 16:51

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_link_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inludetemplate',
            name='include_file',
            field=models.CharField(choices=[('chapter_content', 'Chapter content'), ('chapter_list', 'Chapter list'), ('link', 'Links'), ('novel_info', 'Novel (Comic) detail'), ('novel_list', 'Novel (Comic) list - grid'), ('novel_genres', 'Novel (Comic) genres'), ('breadcrumb', 'Breadcrumb'), ('base_footer_info', 'Base footer info'), ('base_top_menu', 'Base top menu'), ('base_navbar_menu', 'Base navbar menu'), ('base_auth_modal', 'Base auth modal')], max_length=250),
        ),
        migrations.AlterField(
            model_name='inludetemplate',
            name='params',
            field=models.JSONField(blank=True, default=cms.models.json_template_default, null=True),
        ),
        migrations.AlterField(
            model_name='templatemanager',
            name='includes_default',
            field=models.JSONField(blank=True, default=cms.models.json_template_default, null=True),
        ),
        migrations.AlterField(
            model_name='templatemanager',
            name='page_file',
            field=models.CharField(choices=[('index', 'Index - Homepage'), ('chapter', 'chapter'), ('novel', 'Novel (Comic) Infomation'), ('novel_all', 'Novel (Comic) view all'), ('base_footer', 'Base footer'), ('base_navbar', 'Base navbar'), ('base_top_menu', 'Base top menu'), ('base_other_html', 'Base other html')], max_length=250, unique=True),
        ),
    ]
