# Generated by Django 3.1.5 on 2021-01-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20210117_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemanager',
            name='include_params',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templatemanager',
            name='page_file',
            field=models.CharField(choices=[('index', 'index'), ('chapter', 'chapter'), ('novel', 'novel'), ('footer', 'footer'), ('navbar', 'navbar')], max_length=250),
        ),
    ]
