# Generated by Django 3.1.5 on 2021-01-17 14:56

import crawl_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20210117_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='inludetemplate',
            name='code',
            field=models.CharField(default='', max_length=50, validators=[crawl_service.models.code_validate]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templatemanager',
            name='page_file',
            field=models.CharField(choices=[('index', 'index'), ('chapter', 'chapter'), ('novel', 'novel'), ('footer', 'footer'), ('navbar', 'navbar')], max_length=250, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='inludetemplate',
            unique_together={('template', 'code')},
        ),
        migrations.RemoveField(
            model_name='inludetemplate',
            name='values',
        ),
    ]
