# Generated by Django 3.1.5 on 2021-01-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20210117_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatemanager',
            old_name='include_params',
            new_name='includes_default',
        ),
        migrations.AddField(
            model_name='inludetemplate',
            name='include_params',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templatemanager',
            name='page_file',
            field=models.CharField(choices=[('index', 'index'), ('chapter', 'chapter'), ('novel', 'novel'), ('novel_all', 'novel_all'), ('footer', 'footer'), ('navbar', 'navbar')], max_length=250, unique=True),
        ),
    ]
