# Generated by Django 3.1.5 on 2021-01-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20210117_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inludetemplate',
            old_name='include_params',
            new_name='params',
        ),
    ]
