# Generated by Django 3.1.6 on 2021-02-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20210203_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inludetemplate',
            name='include_file',
            field=models.CharField(choices=[('chapter_content', 'Chapter content'), ('chapter_list', 'Chapter list'), ('link', 'Links'), ('novel_info', 'Novel (Comic) detail'), ('novel_list', 'Novel (Comic) list - grid'), ('novel_genres', 'Novel (Comic) genres'), ('breadcrumb', 'Breadcrumb'), ('base_footer_info', 'Base footer info'), ('base_top_menu', 'Base top menu'), ('base_navbar_menu', 'Base navbar menu'), ('base_auth_modal', 'Base auth modal'), ('user_profile', 'User profile'), ('comment', 'Comment')], max_length=250),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='page_file',
            field=models.CharField(choices=[('index', 'Index - Homepage'), ('novel', 'Novel (Comic) Infomation'), ('chapter', 'Chapter'), ('novel_all', 'Novel (Comic) view all'), ('user', 'User'), ('base_footer', 'Base footer'), ('base_navbar', 'Base navbar'), ('base_top_menu', 'Base top menu'), ('base_other_html', 'Base other html')], max_length=250, unique=True),
        ),
    ]
