# Generated by Django 3.1.5 on 2021-01-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_auto_20210117_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='inludetemplate',
            name='full_width',
            field=models.BooleanField(default=False),
        ),
    ]
