# Generated by Django 3.1.6 on 2021-02-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20210219_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='extra_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
