# Generated by Django 3.1.4 on 2020-12-26 04:14

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import novel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'novel_authors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=250, null=True, populate_from='name', slugify=novel.models.unicode_slugify, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'novel_genres',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'novel_status',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=250, null=True, populate_from='name', slugify=novel.models.unicode_slugify, unique=True)),
                ('url', models.TextField()),
                ('thumbnail_image', models.CharField(blank=True, max_length=250, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('chapter_updated', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follow', models.IntegerField(default=0)),
                ('vote', models.FloatField(default=5)),
                ('vote_total', models.IntegerField(default=1)),
                ('view_daily', models.IntegerField(default=0)),
                ('view_monthly', models.IntegerField(default=0)),
                ('view_total', models.IntegerField(default=0)),
                ('authors', models.ManyToManyField(blank=True, db_table='novel_novel_authors_rel', to='novel.Author')),
                ('genres', models.ManyToManyField(blank=True, db_table='novel_novel_genres_rel', to='novel.Genre')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.status')),
            ],
            options={
                'db_table': 'novel_novels',
            },
        ),
        migrations.CreateModel(
            name='NovelChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('url', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=250, null=True, populate_from='name', slugify=novel.models.unicode_slugify)),
                ('view_total', models.IntegerField(default=0, null=True)),
                ('content_updated', models.BooleanField(default=False)),
                ('binary_content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novel')),
            ],
            options={
                'db_table': 'novel_chapters',
                'ordering': ['-id'],
                'unique_together': {('slug', 'novel'), ('name', 'novel')},
            },
        ),
    ]
