# Generated by Django 3.1.6 on 2021-02-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_regex', models.CharField(max_length=250)),
                ('method', models.CharField(max_length=10)),
                ('ip', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'novel_allow_ips',
            },
        ),
    ]
