# Generated by Django 3.1.6 on 2021-02-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_allowip'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='crawl_errors',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='novelchapter',
            name='crawl_errors',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
