# Generated by Django 3.1.4 on 2020-12-31 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_auto_20201230_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='novelchapter',
            options={'ordering': ['id']},
        ),
    ]
