# Generated by Django 3.1.6 on 2021-02-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_auto_20210226_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='hot_point',
            field=models.IntegerField(default=0),
        ),
    ]
