# Generated by Django 3.1.4 on 2021-01-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_auto_20201231_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='latest_chapter_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
