# Generated by Django 3.1.4 on 2021-01-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_novel_latest_chapter_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='thumbnail_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
