# Generated by Django 3.1.5 on 2021-01-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_auto_20210106_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novelchapter',
            options={'ordering': ['-id']},
        ),
    ]
