# Generated by Django 3.1.5 on 2021-01-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0006_auto_20210111_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='chapter_updated',
            new_name='novel_updated',
        ),
        migrations.RenameField(
            model_name='novelchapter',
            old_name='content_updated',
            new_name='chapter_updated',
        ),
    ]
