# Generated by Django 3.1.6 on 2021-03-10 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novel', '0006_auto_20210302_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelAdvertisementPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('base', 'BASE'), ('index', 'INDEX'), ('novel_all', 'NOVEL ALL'), ('novel_info', 'NOVEL INFO'), ('novel_chapter', 'NOVEL CHAPTER')], max_length=50)),
                ('code', models.CharField(choices=[('base_header', 'BASE HEADER'), ('base_top', 'BASE TOP'), ('index_header', 'INDEX HEADER'), ('index_top', 'INDEX TOP'), ('index_sidebar', 'INDEX TOP'), ('novel_all_header', 'NOVEL ALL HEADER'), ('novel_all_top', 'NOVEL ALL TOP'), ('novel_all_end', 'NOVEL ALL END'), ('novel_info_header', 'NOVEL INFO HEADER'), ('novel_info_top', 'NOVEL INFO TOP'), ('novel_info_right', 'NOVEL INFO RIGHT'), ('novel_info_before_chap_list', 'NOVEL INFO BEFORE CHAP LIST'), ('novel_info_after_chap_list', 'NOVEL INFO AFTER CHAP LIST'), ('novel_info_before_comment', 'NOVEL INFO BEFORE COMMENT'), ('novel_chapter_header', 'NOVEL CHAPTER HEADER'), ('novel_chapter_top', 'NOVEL CHAPTER TOP'), ('novel_chapter_before_image', 'NOVEL CHPATER BEFORE IMAGE'), ('novel_chapter_inside_image', 'NOVEL CHPATER INSIDE IMAGE'), ('novel_chapter_after_image', 'NOVEL CHPATER AFTER IMAGE'), ('novel_chapter_before_comment', 'NOVEL CHPATER BEFORE COMMENT')], max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'novel_advertisement_places',
            },
        ),
        migrations.CreateModel(
            name='NovelAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('mobile', 'MOBILE'), ('pc', 'DESKTOP')], default='pc', max_length=50)),
                ('ad_content', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('places', models.ManyToManyField(db_table='novel_adv_adv_place_rel', to='novel.NovelAdvertisementPlace')),
            ],
            options={
                'db_table': 'novel_advertisements',
            },
        ),
    ]
