# Generated by Django 3.1.6 on 2021-03-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_noveladvertisement_noveladvertisementplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noveladvertisement',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
