# Generated by Django 3.1.5 on 2021-01-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_auto_20210111_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_copyright', models.TextField(blank=True, null=True)),
                ('meta_author', models.TextField(blank=True, null=True)),
                ('google_analystics_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'novel_settings',
            },
        ),
    ]
