# Generated by Django 3.1.5 on 2021-01-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_novelsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelsetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='novelsetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
