# Generated by Django 3.1.7 on 2021-03-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0009_auto_20210311_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noveladvertisement',
            name='ad_type',
            field=models.CharField(choices=[('all', 'ALL'), ('mobile', 'MOBILE'), ('pc', 'DESKTOP')], default='all', max_length=50),
        ),
    ]
