# Generated by Django 3.1.5 on 2021-01-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0009_auto_20210111_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelchapter',
            name='images_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
