# Generated by Django 3.1.5 on 2021-01-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0010_novelchapter_images_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelsetting',
            name='novel_type',
            field=models.CharField(choices=[('COMIC', 'Comic'), ('TEXT', 'Text')], default='COMIC', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novelchapter',
            name='images_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
