# Generated by Django 3.1.7 on 2021-03-11 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0010_auto_20210311_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noveladvertisementplace',
            options={'ordering': ('group', 'code')},
        ),
    ]
