# Generated by Django 3.1.5 on 2021-01-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0012_auto_20210116_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelchapter',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='novelchapter',
            unique_together={('slug', 'novel'), ('url', 'novel'), ('name', 'novel')},
        ),
    ]
