# Generated by Django 3.1.5 on 2021-01-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0013_auto_20210116_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelchapter',
            name='binary_content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
