# Generated by Django 3.1.7 on 2021-03-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0014_novelsetting_ads_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelsetting',
            name='robot_txt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
