# Generated by Django 3.1.7 on 2021-03-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0015_novelsetting_robot_txt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novelsetting',
            old_name='robot_txt',
            new_name='robots_txt',
        ),
    ]
