# Generated by Django 3.1.5 on 2021-01-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0015_novelsetting_meta_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelsetting',
            name='domain',
            field=models.CharField(default='', max_length=250),
        ),
    ]
