# Generated by Django 3.1.7 on 2021-03-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0016_auto_20210314_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='thumbnail_image_replace',
            field=models.ImageField(blank=True, null=True, upload_to='images/novels'),
        ),
    ]
