# Generated by Django 3.1.5 on 2021-01-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0016_novelsetting_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelsetting',
            name='domain',
        ),
    ]
