# Generated by Django 3.1.5 on 2021-01-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0017_remove_novelsetting_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelsetting',
            name='img_ignoring',
            field=models.TextField(blank=True, null=True),
        ),
    ]
