# Generated by Django 3.1.5 on 2021-01-21 19:55
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0018_novelsetting_img_ignoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='latest_updated_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
    ]
