# Generated by Django 3.1.7 on 2021-03-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0019_auto_20210321_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelparam',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
