# Generated by Django 3.1.5 on 2021-01-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0019_novel_latest_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelchapter',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='novel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
