# Generated by Django 3.1.5 on 2021-01-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0020_auto_20210121_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelchapter',
            name='active',
        ),
        migrations.AddField(
            model_name='novel',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='novel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
