# Generated by Django 3.1.5 on 2021-01-21 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0017_auto_20210121_2310'),
        ('novel', '0021_auto_20210121_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelchapter',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crawl_service.crawlcampaign'),
            preserve_default=False,
        ),
    ]
