# Generated by Django 3.1.5 on 2021-01-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0022_novelchapter_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='attempt',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='novelchapter',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='novelchapter',
            name='attempt',
            field=models.SmallIntegerField(default=0),
        ),
    ]
