# Generated by Django 3.1.7 on 2021-03-29 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novel', '0022_auto_20210329_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novelsetting',
            old_name='google_analystics_id',
            new_name='google_analytics_id',
        ),
        migrations.AddField(
            model_name='novelsetting',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NovelNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('novel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'novel_notifications',
            },
        ),
    ]
