# Generated by Django 3.1.5 on 2021-01-22 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0017_auto_20210121_2310'),
        ('novel', '0023_auto_20210122_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelchapter',
            name='source',
        ),
        migrations.AddField(
            model_name='novel',
            name='campaign_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crawl_service.crawlcampaignsource'),
            preserve_default=False,
        ),
    ]
