# Generated by Django 3.1.5 on 2021-01-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0024_auto_20210122_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelsetting',
            name='meta_fb_app_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='novelsetting',
            name='meta_og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='novelsetting',
            name='meta_og_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
