# Generated by Django 3.1.7 on 2021-04-06 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0024_auto_20210403_1017'),
        ('novel', '0024_auto_20210402_2226'),
    ]

    operations = [
    ]
