# Generated by Django 3.1.7 on 2021-05-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0025_merge_20210406_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelchapter',
            name='name_index',
            field=models.FloatField(db_index=True, default=-1, null=True),
        ),
    ]
