# Generated by Django 3.1.5 on 2021-01-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0026_auto_20210124_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
