# Generated by Django 3.1.7 on 2021-05-22 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novel', '0026_auto_20210514_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelnotify',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.novelchapter'),
        ),
        migrations.AlterUniqueTogether(
            name='novelnotify',
            unique_together={('user', 'novel', 'chapter', 'notify')},
        ),
    ]
