# Generated by Django 3.1.5 on 2021-01-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0027_auto_20210127_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelUserProfile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('avatar', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'novel_user_profiles',
            },
        ),
    ]
