# Generated by Django 3.1.7 on 2021-06-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0027_auto_20210522_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment'},
        ),
        migrations.AlterModelOptions(
            name='noveladvertisement',
            options={'verbose_name': 'dvertisement'},
        ),
        migrations.AlterModelOptions(
            name='noveladvertisementplace',
            options={'ordering': ('group', 'code'), 'verbose_name': 'Advertisement place'},
        ),
        migrations.AlterModelOptions(
            name='novelreport',
            options={'verbose_name': 'Report'},
        ),
        migrations.AlterModelOptions(
            name='novelsetting',
            options={'verbose_name': 'Setting'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'statu'},
        ),
    ]
