# Generated by Django 3.1.5 on 2021-02-02 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0018_cdnserver'),
        ('novel', '0028_noveluserprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDNNovelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('hash_origin_url', models.CharField(db_index=True, max_length=250)),
                ('url', models.TextField(blank=True, null=True)),
                ('retry', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full', models.BooleanField(default=False)),
                ('cdn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl_service.cdnserver')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.novelchapter')),
            ],
            options={
                'db_table': 'cdn_novel_files',
                'unique_together': {('cdn', 'hash_origin_url')},
            },
        ),
    ]
