# Generated by Django 3.1.6 on 2021-02-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0029_cdnnovelfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdnnovelfile',
            name='allow_limit',
            field=models.BooleanField(default=False),
        ),
    ]
