# Generated by Django 3.1.12 on 2021-07-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0029_novel_related_novel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='related_novel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.novel'),
        ),
    ]
