# Generated by Django 3.1.6 on 2021-02-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0030_cdnnovelfile_allow_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdnnovelfile',
            name='url_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
