# Generated by Django 3.1.6 on 2021-02-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0030_auto_20210203_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='novelchapter',
            options={},
        ),
    ]
