# Generated by Django 3.1.6 on 2021-02-05 01:43

from django.db import migrations, models
import django.db.models.deletion
import novel.models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0031_auto_20210204_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelFlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_chapter', models.JSONField(blank=True, default=novel.models.default_novel_flat, null=True)),
                ('first_chapter', models.JSONField(blank=True, default=novel.models.default_novel_flat, null=True)),
                ('chapters', models.JSONField(blank=True, default=novel.models.default_novel_flat, null=True)),
            ],
            options={
                'db_table': 'novel_novels_flat',
            },
        ),
        migrations.AddField(
            model_name='novelchapter',
            name='novel_slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='novel_flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.novelflat', unique=True),
        ),
    ]
