# Generated by Django 3.1.6 on 2021-02-05 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0032_auto_20210205_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novelchapter',
            options={'ordering': ['-id']},
        ),
    ]
