# Generated by Django 3.1.6 on 2021-02-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0034_auto_20210207_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novelchapter',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='cdnnovelfile',
            name='allow_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cdnnovelfile',
            name='url_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
