# Generated by Django 3.1.6 on 2021-02-07 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0034_auto_20210205_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='latest_updated_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
