# Generated by Django 3.1.6 on 2021-02-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0036_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply_to',
            new_name='reply_id',
        ),
    ]
