# Generated by Django 3.1.6 on 2021-02-13 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0037_auto_20210210_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlNovelRetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novelchapter', unique=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novel', unique=True)),
            ],
            options={
                'db_table': 'crawl_novel_retry',
            },
        ),
    ]
