# Generated by Django 3.1.6 on 2021-02-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0038_crawlnovelretry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlnovelretry',
            name='chapter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='novel.novelchapter'),
        ),
        migrations.AlterField(
            model_name='crawlnovelretry',
            name='novel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='novel.novel'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='novel_flat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.novelflat'),
        ),
    ]
