# Generated by Django 3.1.6 on 2021-02-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0040_novel_hot_novel'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlnovelretry',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
    ]
