# Generated by Django 3.1.6 on 2021-02-18 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novel', '0042_bookmark_history_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='novel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='novel.novel'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('user', 'novel')},
        ),
    ]
