# Generated by Django 3.1.6 on 2021-02-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0043_auto_20210218_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='hot_point',
            field=models.IntegerField(default=0),
        ),
    ]
