# Generated by Django 3.1.6 on 2021-02-23 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0022_cdnserver_last_run'),
        ('novel', '0043_auto_20210218_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='src_campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crawl_service.crawlcampaignsource'),
        ),
    ]
