# Generated by Django 3.1.6 on 2021-02-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0044_auto_20210223_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='src_campaign',
            field=models.CharField(default='', max_length=50),
        ),
    ]
