# Generated by Django 3.1.4 on 2020-12-18 16:41

import crawl_service.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlCampaignSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('homepage', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'crawl_campaign_sources',
            },
        ),
        migrations.CreateModel(
            name='CrawlCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(choices=[('STORY', 'STORY'), ('STORY_INFO', 'STORY_INFO'), ('CHAPTER_INFO', 'CHAPTER_INFO')], max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('target_url', models.CharField(max_length=250)),
                ('page_param_name', models.CharField(blank=True, default='', help_text='Blank if no pagination.', max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('campaign_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl_service.crawlcampaignsource')),
            ],
            options={
                'db_table': 'crawl_campaigns',
            },
        ),
        migrations.CreateModel(
            name='CrawlItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, validators=[crawl_service.models.code_validate])),
                ('parent_code', models.CharField(blank=True, max_length=50, null=True, validators=[crawl_service.models.code_validate])),
                ('xpath', models.CharField(max_length=250)),
                ('ignore_duplication', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl_service.crawlcampaign')),
            ],
            options={
                'db_table': 'crawl_campaign_items',
                'unique_together': {('campaign', 'code')},
            },
        ),
    ]
