# Generated by Django 3.1.4 on 2020-12-03 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('source_url', models.CharField(max_length=250)),
                ('pagination', models.BooleanField(default=False)),
                ('page_format', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'crawl_campaigns',
            },
        ),
        migrations.CreateModel(
            name='CrawlItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('xpath', models.CharField(max_length=250)),
                ('xpath_property', models.CharField(max_length=50)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl_service.crawlcampaign')),
            ],
            options={
                'db_table': 'crawl_campaign_items',
            },
        ),
    ]
