# Generated by Django 3.1.4 on 2020-12-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlcampaign',
            old_name='page_param_name',
            new_name='pagination_param',
        ),
    ]
