# Generated by Django 3.1.4 on 2021-01-02 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crawl_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlitem',
            name='ignore_duplication',
        ),
        migrations.AlterField(
            model_name='crawlcampaign',
            name='campaign_type',
            field=models.CharField(choices=[], max_length=50),
        ),
        migrations.CreateModel(
            name='CrawlItemAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_item_code', models.CharField(max_length=250)),
                ('action', models.CharField(choices=[], max_length=250)),
                ('params', models.CharField(blank=True, max_length=250, null=True)),
                ('campaign',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl_service.crawlcampaign')),
            ],
            options={
                'db_table': 'crawl_campaign_actions',
            },
        ),
    ]
