# Generated by Django 3.1.4 on 2020-12-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0002_auto_20201203_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlitem',
            old_name='parent',
            new_name='parent_code',
        ),
    ]
