# Generated by Django 3.1.4 on 2020-12-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0002_auto_20201224_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlcampaign',
            old_name='pagination_param',
            new_name='paging_param',
        ),
        migrations.AddField(
            model_name='crawlcampaign',
            name='paging_delay',
            field=models.IntegerField(default=0),
        ),
    ]
