# Generated by Django 3.1.4 on 2021-01-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0002_auto_20210102_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('NOVEL', 'NOVEL'), ('NOVEL_INFO', 'NOVEL_INFO'), ('NOVEL_CHAPTER', 'NOVEL_CHAPTER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='crawlitemaction',
            name='action',
            field=models.CharField(choices=[('Reverse', 'Reverse')], max_length=250),
        ),
    ]
