# Generated by Django 3.1.4 on 2020-12-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0003_auto_20201224_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlcampaign',
            name='paging_delay',
            field=models.IntegerField(default=0, help_text='If the target url has pagination, this option will allow to delay any second after each request'),
        ),
    ]
