# Generated by Django 3.1.4 on 2020-12-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0003_auto_20201203_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlcampaign',
            name='page_format',
        ),
        migrations.RemoveField(
            model_name='crawlcampaign',
            name='pagination',
        ),
        migrations.AddField(
            model_name='crawlcampaign',
            name='page_limit',
            field=models.IntegerField(default=0, help_text='Set 0 want for dynamic redirect page with page param name.'),
        ),
        migrations.AddField(
            model_name='crawlcampaign',
            name='page_param_name',
            field=models.CharField(blank=True, default='', help_text='Blank if no pagination.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crawlcampaign',
            name='source_url',
            field=models.CharField(help_text='\n                                  HTTP url or format <campaign_code>.<item_code> to get urls from campaign parent', max_length=250),
        ),
    ]
