# Generated by Django 3.1.4 on 2020-12-03 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0004_auto_20201203_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlcampaign',
            name='source_url',
            field=models.CharField(help_text='HTTP url or use format [campaign_code].[item_code] to get urls from campaign parent', max_length=250),
        ),
        migrations.AlterField(
            model_name='crawlitem',
            name='xpath_property',
            field=models.CharField(blank=True, help_text='@src, @href, text(), html(). Blank if parent item.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CrawlCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ignore', 'IGNORE')], max_length=10)),
                ('item_code', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('eq', 'Equal'), ('lt', 'Less than'), ('gt', 'Great than'), ('ct', 'Contain'), ('dup', 'Is duplicate')], max_length=10)),
                ('value', models.CharField(blank=True, max_length=250, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl_service.crawlcampaign')),
            ],
            options={
                'db_table': 'crawl_campaign_conditions',
            },
        ),
    ]
