# Generated by Django 3.1.4 on 2020-12-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0005_auto_20201203_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlitem',
            name='storage',
            field=models.BooleanField(default=False),
        ),
    ]
