# Generated by Django 3.1.4 on 2020-12-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0005_crawlcampaign_target_direct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crawlitem',
            unique_together={('campaign', 'code', 'parent_code')},
        ),
    ]
