# Generated by Django 3.1.4 on 2021-01-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0006_auto_20210105_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlitemaction',
            name='crawl_item_code',
        ),
        migrations.AlterField(
            model_name='crawlitemaction',
            name='action',
            field=models.CharField(choices=[('Reverse', 'Reverse'), ('FormatChapterContent', 'FormatChapterContent'), ('GroupItem', 'GroupItem')], max_length=250),
        ),
    ]
