# Generated by Django 3.1.4 on 2020-12-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0006_crawlitem_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlCampaignItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_code', models.CharField(db_index=True, max_length=50)),
                ('item_code', models.CharField(db_index=True, max_length=50)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crawl_campaign_item_datas',
                'unique_together': {('campaign_code', 'item_code')},
            },
        ),
    ]
