# Generated by Django 3.1.4 on 2020-12-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0007_crawlcampaignitemdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlcampaign',
            name='api_url',
            field=models.CharField(blank=True, help_text='API receive data from campaign with POST method', max_length=250, null=True),
        ),
    ]
