# Generated by Django 3.1.4 on 2020-12-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0007_auto_20201225_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlcampaign',
            name='last_run',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='crawlcampaign',
            name='repeat_time',
            field=models.IntegerField(default=5, help_text='Minutes to repeat this campaign, set 0 if dont want to repeat'),
        ),
        migrations.AlterField(
            model_name='crawlcampaign',
            name='status',
            field=models.CharField(choices=[('running', 'RUNNING'), ('stopped', 'STOPPED')], max_length=10),
        ),
        migrations.AlterField(
            model_name='crawlcampaign',
            name='target_direct',
            field=models.BooleanField(default=True, help_text='If option is TRUE, this campaign will call directly by target_url otherwise call via API and get list of urls from response.'),
        ),
    ]
