# Generated by Django 3.1.4 on 2021-01-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0008_auto_20210106_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlcampaign',
            name='run_synchonize',
            field=models.BooleanField(default=True),
        ),
    ]
