# Generated by Django 3.1.4 on 2020-12-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0008_auto_20201225_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('NOVEL', 'NOVEL'), ('NOVEL_INFO', 'NOVEL_INFO'), ('NOVEL_CHAPTER', 'NOVEL_CHAPTER')], max_length=50),
        ),
    ]
