# Generated by Django 3.1.5 on 2021-01-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0009_crawlcampaign_run_synchonize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlitemaction',
            name='action',
            field=models.CharField(choices=[('Reverse Chapter List', 'Reverse Chapter List'), ('Format Chapter Content', 'Format Chapter Content'), ('Group Items', 'Group Items'), ('Join Items', 'Join Items')], max_length=250),
        ),
    ]
