# Generated by Django 3.1.4 on 2020-12-04 06:34

import crawl_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0009_auto_20201203_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, validators=[crawl_service.models.code_validate])),
                ('name', models.CharField(max_length=250)),
                ('homepage', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'crawl_source',
            },
        ),
        migrations.AlterUniqueTogether(
            name='crawlitem',
            unique_together={('campaign', 'parent_code', 'code')},
        ),
    ]
