# Generated by Django 3.1.4 on 2020-12-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0010_auto_20201204_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlcampaign',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crawl_service.crawlsource'),
            preserve_default=False,
        ),
    ]
