# Generated by Django 3.1.4 on 2020-12-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0011_crawlcampaign_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrawlCampaignItemData',
        ),
        migrations.RemoveField(
            model_name='crawlitem',
            name='storage',
        ),
        migrations.AddField(
            model_name='crawlitem',
            name='hash_function',
            field=models.CharField(blank=True, choices=[('md5', 'MD5')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crawlitem',
            name='key_store',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
