# Generated by Django 3.1.4 on 2020-12-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0012_auto_20201204_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlitem',
            name='name',
        ),
    ]
