# Generated by Django 3.1.5 on 2021-01-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0012_remove_crawlcampaign_paging_stopped_by_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlcampaign',
            name='no_update_limit',
            field=models.BooleanField(default=0, help_text='Default = 0 is no limit'),
        ),
    ]
