# Generated by Django 3.1.5 on 2021-01-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0013_crawlcampaign_no_update_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlcampaign',
            name='no_update_limit',
            field=models.IntegerField(default=0, help_text='Default = 0 is no limit'),
        ),
    ]
