# Generated by Django 3.1.4 on 2020-12-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0013_remove_crawlitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlcondition',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='crawlcondition',
            name='value',
        ),
        migrations.RemoveField(
            model_name='crawlitem',
            name='hash_function',
        ),
        migrations.RemoveField(
            model_name='crawlitem',
            name='key_store',
        ),
        migrations.AlterField(
            model_name='crawlcondition',
            name='action',
            field=models.CharField(choices=[('remove_duplicate', 'REMOVE DUPLICATE'), ('md5_hash', 'MD5'), ('storage', 'STORAGE')], max_length=50),
        ),
    ]
