# Generated by Django 3.1.4 on 2020-12-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0014_auto_20201204_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlcondition',
            name='params',
            field=models.CharField(default='', max_length=250),
        ),
    ]
