# Generated by Django 3.1.4 on 2020-12-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0015_crawlcondition_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlitem',
            name='ignore_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crawlcondition',
            name='action',
            field=models.CharField(choices=[('check_dupplicate', 'CHECK DUPLICATE')], max_length=50),
        ),
    ]
