# Generated by Django 3.1.5 on 2021-01-21 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0016_auto_20210120_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('NovelCampaignType', 'NOVEL'), ('NovelInfoCampaignType', 'NOVEL_INFO'), ('NovelChapterCampaignType', 'NOVEL_CHAPTER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='crawlitemaction',
            name='action',
            field=models.CharField(choices=[('ReverseAction', 'Reverse Chapter List'), ('FormatChapterContent', 'Format Chapter Content'), ('GroupItem', 'Group Items'), ('JoinItem', 'Join Items')], max_length=250),
        ),
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.TextField(blank=True, max_length=250, null=True)),
                ('crawled_data', models.JSONField(blank=True, null=True)),
                ('log', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl_service.crawlcampaign')),
            ],
            options={
                'db_table': 'crawl_campaign_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
