# Generated by Django 3.1.5 on 2021-01-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0017_auto_20210121_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDNServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('server_id', models.CharField(blank=True, max_length=250, null=True)),
                ('endpoint', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cdn_server',
                'ordering': ['name'],
            },
        ),
    ]
