# Generated by Django 3.1.6 on 2021-02-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_service', '0021_auto_20210208_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdnserver',
            name='last_run',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
